apiVersion: v1
kind: Service
metadata:
  name: fastapi-metrics
  labels:
    app: fastapi-metrics
spec:
  selector:
    app: fastapi-metrics
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  type: ClusterIP
